### ISSUE TITLE
Check Event Error

### ISSUE THREAD

**Issue by pratamarama** [macif-dev/ssl_pinning_plugin#11]
I got this error when check ssl pinning

ssl_pinning_plugin: 1.4.0
Android 6.0 or earlier

[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoClassDefFoundError: com.macif.plugin.sslpinningplugin.SslPinningPlugin$handleCheckEvent$get$1

E/flutter (15888): 	at com.macif.plugin.sslpinningplugin.SslPinningPlugin.handleCheckEvent(SslPinningPlugin.kt:78)
E/flutter (15888): 	at com.macif.plugin.sslpinningplugin.SslPinningPlugin.onMethodCall(SslPinningPlugin.kt:57)
E/flutter (15888): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (15888): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (15888): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (15888): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (15888): 	at android.os.MessageQueue.next(MessageQueue.java:148)

Anyone can help me?

**Comment by NguyenDinhTruong97** [comment]
I got same error. App crash when check ssl pinning. Any update on this, please? Thanks
Here is the log from firebase crashlytics
<img width="423" alt="Screen Shot 2022-02-28 at 09 03 13" src="https://user-images.githubusercontent.com/40660913/155913011-5e5b2fc9-4d2a-4c11-a8e5-1095259fabc3.png">

Fatal Exception: java.lang.NoClassDefFoundError: e9.b
       at com.macif.plugin.sslpinningplugin.SslPinningPlugin.handleCheckEvent(SslPinningPlugin.java)
       at com.macif.plugin.sslpinningplugin.SslPinningPlugin.onMethodCall(SslPinningPlugin.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java)
       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:150)
       at android.os.Looper.loop(Looper.java:139)
       at android.app.ActivityThread.main(ActivityThread.java:5541)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by alex596** [comment]
Hello, this plugin is no longer maintained because the SSL_Pinning test is now possible directly from the http_client or from Dio.

See https://api.flutter.dev/flutter/dart-io/SecurityContext-class.html
