### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError: c.f.a.a.a$c

### ISSUE THREAD

**Issue by 96MayankJain** [macif-dev/ssl_pinning_plugin#16]
We have facing crash on live application. Please check the logs 

- Operating system Version: 6.0.1
- Plugin version: 1.5.0

Fatal Exception: java.lang.NoClassDefFoundError: c.f.a.a.a$c
       at com.macif.plugin.sslpinningplugin.SslPinningPlugin.checkConnexion(SslPinningPlugin.java)
       at com.macif.plugin.sslpinningplugin.SslPinningPlugin.onMethodCall(SslPinningPlugin.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.getStackTrace(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.handleError(DartMessenger.java)
       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:141)
       at android.app.ActivityThread.main(ActivityThread.java:5603)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by us3soap** [comment]
Hi,

Can you test with the 2.0.0 version ?

If not, do you have more details on the scenario to perform to reproduce the bug?

**Comment by 96MayankJain** [comment]
https://user-images.githubusercontent.com/4171272/115200410-d2516e00-a111-11eb-8e13-f3c757995bc3.mov

Its happening with live application. It was working fine before. I am sharing the stack trace from crashlytics

**Comment by us3soap** [comment]
The version of Flutter is the new stable ?

**Comment by 96MayankJain** [comment]
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (2 weeks ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2

**Comment by us3soap** [comment]
With Flutter 2.0.4, can you try the new version of the plugin (2.0.0) ?

**Comment by us3soap** [comment]
Is it still relevant today?

**Comment by dokinkon** [comment]
I just tried with this plugin (2.0.0) with Android 6.0 (emulator). And this crash issue still happened.

I/art     ( 4750): Rejecting re-init on previously-failed class java.lang.Class<com.macif.plugin.sslpinningplugin.SslPinningPlugin$handleCheckEvent$get$1>
E/AndroidRuntime( 4750): FATAL EXCEPTION: main
E/AndroidRuntime( 4750): Process: com.example.example, PID: 4750
E/AndroidRuntime( 4750): java.lang.NoClassDefFoundError: com.macif.plugin.sslpinningplugin.SslPinningPlugin$handleCheckEvent$get$1
E/AndroidRuntime( 4750): 	at com.macif.plugin.sslpinningplugin.SslPinningPlugin.handleCheckEvent(SslPinningPlugin.kt:78)
E/AndroidRuntime( 4750): 	at com.macif.plugin.sslpinningplugin.SslPinningPlugin.onMethodCall(SslPinningPlugin.kt:57)
E/AndroidRuntime( 4750): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 4750): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 4750): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime( 4750): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 4750): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/AndroidRuntime( 4750): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4750): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime( 4750): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4750): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime( 4750): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Thanks.

**Comment by dokinkon** [comment]
> We are facing the crash since yesterday on live application. Please check the logs @us3soap @adsellor
> 
> * Operating system Version: 6.0.1
> * Plugin version: 1.5.0
> 
> Fatal Exception: java.lang.NoClassDefFoundError: c.f.a.a.a$c
> at com.macif.plugin.sslpinningplugin.SslPinningPlugin.checkConnexion(SslPinningPlugin.java)
> at com.macif.plugin.sslpinningplugin.SslPinningPlugin.onMethodCall(SslPinningPlugin.java)
> at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.getStackTrace(MethodChannel.java)
> at io.flutter.embedding.engine.dart.DartMessenger.handleError(DartMessenger.java)
> at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java)
> at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
> at android.os.MessageQueue.next(MessageQueue.java:323)
> at android.os.Looper.loop(Looper.java:141)
> at android.app.ActivityThread.main(ActivityThread.java:5603)
> at java.lang.reflect.Method.invoke(Method.java)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

Hi @96MayankJain 

I just create this PR https://github.com/macif-dev/ssl_pinning_plugin/pull/17

If you are urgent on this issue, maybe it worth a try. :)
