### ISSUE TITLE
ANRs on handleCheckEvent

### ISSUE THREAD

**Issue by NguyenDinhTruong97** [macif-dev/ssl_pinning_plugin#20]
I got this log in firebase crashlytics. 

SslPinningPlugin.java
com.macif.plugin.sslpinningplugin.SslPinningPlugin.handleCheckEvent

Triggered ANR - Root blocking

main (waiting): tid=1 systid=7551
       _at sun.misc.Unsafe.park(Unsafe.java)_
       _at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1723)
       at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3446)
       at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1752)
       at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1923)_
       **at com.macif.plugin.sslpinningplugin.SslPinningPlugin.handleCheckEvent(SslPinningPlugin.java)
       at com.macif.plugin.sslpinningplugin.SslPinningPlugin.onMethodCall(SslPinningPlugin.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java)
       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java)**
       _at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:339)
       at android.os.Looper.loop(Looper.java:208)
       at android.app.ActivityThread.main(ActivityThread.java:8218)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)_
       
This happened mostly in android 11 and 12
<img width="438" alt="Screen Shot 2022-03-02 at 11 27 28" src="https://user-images.githubusercontent.com/40660913/156295042-e1e515fe-87af-488f-a943-c80e201880f5.png">

Anyone can help me with this issue? Thank you very much

**Comment by parakramadr** [comment]
I am facing the same issue. Anyone can please help me with this issue? Thank you very much

**Comment by devmansanket** [comment]
Same Issue.. How to fix? Any updates?
