### ISSUE TITLE
MissingPluginException(No implementation found for method close on channel ssl_pinning_plugin)

### ISSUE THREAD

**Issue by andrewbiller** [macif-dev/ssl_pinning_plugin#7]
New project with main.dart from example doesn't work when check button is pressed for any https site/fingerprint.

Error returned:

MissingPluginException(No implementation found for method close on channel ssl_pinning_plugin)

![image](https://user-images.githubusercontent.com/4090466/85065057-e9869e80-b182-11ea-9ef8-7b9ca731e898.png)

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [versÃ£o
    10.0.18363.900], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.37.0)
[√] Connected device (1 available)

• No issues found!
```

**Comment by andrewbiller** [comment]
[bug_example.zip](https://github.com/macif-dev/ssl_pinning_plugin/files/4800858/bug_example.zip)

**Comment by andrewbiller** [comment]
The problem happens only with Android devices. 
Kotlin libs are outdated in the project

**Comment by furkankadioglu** [comment]
@us3soap Same here. Will you check?

**Comment by us3soap** [comment]
hello, we are working on a fix right now. it will be available soon.

**Comment by B3nac** [comment]
Thank you for working on this bug. I'm getting the same result.

```
2020-07-22 20:38:52.680 15130-15179/com.flutterb3nacapp E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method check on channel ssl_pinning_plugin)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
    #2      SslPinningPlugin.check (package:ssl_pinning_plugin/ssl_pinning_plugin.dart:33:34)
    #3      _MyHomePageState.testPin (package:flutterb3nacapp/main.dart:88:24)
    #4      new _MyHomePageState (package:flutterb3nacapp/main.dart:62:5)
    #5      MyHomePage.createState (package:flutterb3nacapp/main.dart:52:37)
    #6      new StatefulElement (package:flutter/src/widgets/framework.dart:4600:25)
    #7      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:896:38)
    #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:40)
    #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:14)
    #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
    #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
    #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
    #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
    #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
    #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
    #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:14)
    #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
    #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:14)
    #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
    #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
    #26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
    #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
    #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
    #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4675:11)
    #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
    #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
    #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:14)
    #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
    #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:14)
    #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
    #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
    #40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
    #41     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
    #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
    #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4675:11)
    #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
    #45     Element.

```

**Comment by us3soap** [comment]
Hello, I have just delivered version 1.3.0 to you.

Do not hesitate to tell me if there is still a problem.
